/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ivan_healthcare_healthcare_android_util_crypt_Crypter */

#ifndef _Included_com_ivan_healthcare_healthcare_android_util_crypt_Crypter
#define _Included_com_ivan_healthcare_healthcare_android_util_crypt_Crypter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ivan_healthcare_healthcare_android_util_crypt_Crypter
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ivan_healthcare_healthcare_1android_util_crypt_Crypter_encrypt
  (JNIEnv *env, jclass cls, jstring str);

/*
 * Class:     com_ivan_healthcare_healthcare_android_util_crypt_Crypter
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ivan_healthcare_healthcare_1android_util_crypt_Crypter_decrypt
  (JNIEnv *env, jclass cls, jstring str);

#ifdef __cplusplus
}
#endif
#endif
